### PR TITLE
Replacing chapter w/ group or local group & removing unused files.

### LINKED ISSUE #39: Do 'chapter' clean up
I am currently working on a clean up of 'chapter' throughout this repo

### PR DESCRIPTION
**Pull request by jackiekazil**
This PR does 2 things. 
* Replaces chapter w/ group or local group. 
* Removes unused files. 

fixes #39

### CODE REVIEW

**Comment by econchick** [comment]
Thanks so much, @jackiekazil !  I did a `grep -i "chapter" -r .` from within `pyladies-kit` directory, and I didn't find anything else.  Once this is merged (like, a few minutes after), changes will reflect on kit.pyladies.com, but I still have to do a release on PyPI (not automatic yet).  I have time tomorrow in which I will do just that!

**Comment by jackiekazil** [comment]
:+1:

**Comment by econchick** [comment]
@jackiekazil sorry it took me an extra day - but all should be good!  

```bash
(env) $ pip install pyladies
(env) $ pyladies --version
2.0.4
```

**Comment by jackiekazil** [comment]
No worries!

And YAY!

On Wed, Aug 5, 2015 at 11:43 AM, Lynn Root <notifications@github.com> wrote:

> @jackiekazil <https://github.com/jackiekazil> sorry it took me an extra
> day - but all should be good!
>
> (env) $ pip install pyladies
> (env) $ pyladies --version
> 2.0.4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyladies/pyladies-kit/pull/40#issuecomment-128045256>.
>



-- 
Jacqueline Kazil | @jackiekazil

**Pull request merged**
